two_d_mode: true

# robot_localization produces transform from world frame to base_link frame
map_frame: map
odom_frame: odom
base_link_frame: base_link

# Wheel odometry
# We discard position estimates from wheel odometry
# because the same data is already reported in velocity
odom0: /move_base_controller/odom
odom0_config: [false, false, false, # x, y, z
               false, false, false, # r, p, y
               true,  true, false,   # dx, dy, dz
               false, false, true,  # dr, dp, dy
               false, false, false] # d^2x, d^2y, d^2z

# Body IMU
imu0: /imu_data
imu0_config: [false, false, false,
              false, false, true,
              false, false, false,
              false, false, true,
              true, false, false]

world_frame: odom
