footprint: [[0.359537, 0.34925], [0.359537, -0.34925], [-0.359537, -0.34925], [-0.359537, 0.34925]]
transform_tolerance: 0.5

obstacle_range: 2.5
raytrace_range: 3.0

observation_sources: front_lidar 

front_lidar: {sensor_frame: laser_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}

